version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ./client:/app  # React projesini bağlama
    environment:
      - CHOKIDAR_USEPOLLING=true  # Dosya izleme için polling ayarı

volumes:
  pgdata:
